# Generated by Django 3.0.7 on 2020-06-09 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_item_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='ordered_date',
        ),
    ]
